### ISSUE TITLE
nextchat对接好像有点问题

### ISSUE THREAD

**Issue by yanquan2020** [LLM-Red-Team/emohaa-free-api#3]
回答一直显示“我不理解你的意思,换个话题吧”

**Comment by Vinlic** [comment]
@yanquan2020 需要提供上下文，确认是否是对话合并导致的问题

**Comment by dqzboy** [comment]
使用chatgpt-web同样的问题
<img width="1247" alt="image" src="https://github.com/LLM-Red-Team/emohaa-free-api/assets/42825450/2d7a8121-0866-4923-b490-0f065b4d0fe7">
<img width="941" alt="image" src="https://github.com/LLM-Red-Team/emohaa-free-api/assets/42825450/bdd8598a-6fc4-4faf-b685-68a9bc3cf76e">
